
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Sep 13 20:58:36 CST 2016
//----------------------------------------------------

package VisualBasic;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAR_DER = 49;
  public static final int FUNCTION = 15;
  public static final int OP_MENOR_QUE = 21;
  public static final int ENTERO = 4;
  public static final int ENTERO_LITERAL = 50;
  public static final int OP_NOT = 26;
  public static final int PRIVATE = 13;
  public static final int OP_AND = 24;
  public static final int CADENA_LITERAL = 53;
  public static final int OP_MULTIPLICACION = 29;
  public static final int FOR = 37;
  public static final int WRITE = 2;
  public static final int BOOLEAN_LITERAL = 55;
  public static final int IDENTIFICADOR = 54;
  public static final int REAL_LITERAL = 51;
  public static final int CARACTER = 7;
  public static final int TYPE = 9;
  public static final int CALL = 17;
  public static final int UNTIL = 44;
  public static final int LOOP = 41;
  public static final int NEXT = 40;
  public static final int EXIT = 16;
  public static final int ELSE_IF = 35;
  public static final int IF = 32;
  public static final int DIM = 10;
  public static final int EOF = 0;
  public static final int BOOLEAN = 6;
  public static final int BYVAL = 19;
  public static final int OP_DIVISION = 30;
  public static final int error = 1;
  public static final int COMA = 45;
  public static final int CADENA = 8;
  public static final int OP_OR = 25;
  public static final int OP_RESTA = 28;
  public static final int PAR_IZQ = 48;
  public static final int REAL = 5;
  public static final int CARACTER_LITERAL = 52;
  public static final int FIN_LINEA = 47;
  public static final int OP_MAYOR_IGUAL_QUE = 22;
  public static final int ELSE = 34;
  public static final int PUNTO = 46;
  public static final int BYREF = 18;
  public static final int OP_IGUAL = 31;
  public static final int READ = 3;
  public static final int TO = 38;
  public static final int WHILE = 43;
  public static final int PUBLIC = 12;
  public static final int OP_MAYOR_QUE = 20;
  public static final int THEN = 33;
  public static final int END = 36;
  public static final int OP_SUMA = 27;
  public static final int OP_MENOR_IGUAL_QUE = 23;
  public static final int AS = 11;
  public static final int SUB = 14;
  public static final int DO = 42;
  public static final int STEP = 39;
}

